apiVersion: apps/v1
kind: Deployment
metadata:
  name: estadisticas-service
  labels:
    app: estadisticas-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estadisticas-service
  template:
    metadata:
      labels:
        app: estadisticas-service
    spec:
      containers:
      - name: estadisticas-service
        image: 605493908341.dkr.ecr.us-east-1.amazonaws.com/estadisticas-service:latest
        ports:
        - containerPort: 8006
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: estadisticas-service
spec:
  type: ClusterIP
  selector:
    app: estadisticas-service
  ports:
  - port: 8006
    targetPort: 8006